### PR TITLE
Change to use new client ids

### PR DESCRIPTION
**Pull request by emma-brainlabs**

### CODE REVIEW

**Comment by james-d-f** [comment]
Seen, not a high priority to update, since only us two use it.

**Comment by emma-brainlabs** [comment]
True (I guess engineering don't actually write tools anymore, so is only your team and my team it is relevant for). Is it easy to update the deployment? I'm happy to run `make deploy` if that is what is needed?

Otherwise I will be maintaining this branch as a local deployment 😂

**Comment by james-d-f** [comment]
I seem to recall having some issues updating it last time I looked at it. But it is supposed to update to PyPI so it can be installed/updated by pip, which only I can do.

**Review by james-d-f — APPROVED** [review]
Merging it, but not committing to actually updating the tool

**Pull request merged**
